### ISSUE TITLE
我这种多标签适用吗，labels里面多个标签

### ISSUE THREAD

**Issue by chenyang9799** [yang-ruixin/PyTorch-Image-Models-Multi-Label-Classification#7]
**我的：**
img_name | labels
-- | --
Z_SURF_I_57682_20200901000000_O_AWS_WLPD-10-01.jpg | NONE
Z_SURF_I_57682_20200901030000_O_AWS_WLPD-10-01.jpg | NONE
Z_SURF_I_57682_20200901060000_O_AWS_WLPD-10-01.jpg | Cu hum;Fc
Z_SURF_I_57682_20200901090000_O_AWS_WLPD-10-01.jpg | NONE
Z_SURF_I_57682_20200902000000_O_AWS_WLPD-10-01.jpg | NONE
Z_SURF_I_57682_20200902030000_O_AWS_WLPD-10-01.jpg | Cu hum;Fc;Ac tra
Z_SURF_I_57682_20200902060000_O_AWS_WLPD-10-01.jpg | Ac tra;Sc tra
Z_SURF_I_57682_20200902090000_O_AWS_WLPD-10-01.jpg | Ac tra
Z_SURF_I_57682_20200903000000_O_AWS_WLPD-10-01.jpg | Cu hum;Fc
Z_SURF_I_57682_20200903030000_O_AWS_WLPD-10-01.jpg | NONE
Z_SURF_I_57682_20200903060000_O_AWS_WLPD-10-01.jpg | Cu hum;Fc
Z_SURF_I_57682_20200903090000_O_AWS_WLPD-10-01.jpg | Ci dens;Ac tra

**你的：**

image_path | gender | article | color
-- | -- | -- | --
./fashion-product-images/images/23737.jpg | Women | Sunglasses | Black
./fashion-product-images/images/25077.jpg | Men | Accessory Gift Set | Navy Blue
./fashion-product-images/images/34345.jpg | Men | Tshirts | Purple
./fashion-product-images/images/15266.jpg | Women | Casual Shoes | Gold
./fashion-product-images/images/15972.jpg | Men | Shirts | Blue
./fashion-product-images/images/33111.jpg | Women | Casual Shoes | Yellow
./fashion-product-images/images/56524.jpg | Women | Lipstick | Purple
./fashion-product-images/images/9112.jpg | Men | Sports Shoes | White
./fashion-product-images/images/58961.jpg | Men | Perfume and Body Mist | White

**Comment by yang-ruixin** [comment]
你好，任务不完全一样，你需要自己改些代码，请参考下面这篇文章
https://learnopencv.com/multi-label-image-classification-with-pytorch-image-tagging/

**Comment by chenyang9799** [comment]
谢谢大佬，不修改代码，这样行不行？转化成多个标签的二分类问题，你的是多标签的多分类：

image_path | Ac cug | Ac flo | Ac op | Ac tra | As op | As tra | Cb cap | Cc | Ci dens | Ci fil | Cs fil | Cu hum | Fc | Fn | NONE | Ns | Sc cug | Sc op | Sc tra
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Z_SURF_I_57780_20200412090000_O_AWS_WLPD-10-01.jpg | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0
Z_SURF_I_57845_20200429030000_O_AWS_WLPD-10-01.jpg | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0
Z_SURF_I_57774_20200625030000_O_AWS_WLPD-10-01.jpg | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0

**Comment by yang-ruixin** [comment]
可以的，而且不需要NONE那列，如果所有标签都是0，就自动就是NONE了

**Comment by chenyang9799** [comment]
评估完了，效果不太理想，因为我的训练集类别不均衡，有的类别数据很多有的很少，大佬有什么解决办法吗

**Comment by yang-ruixin** [comment]
> 评估完了，效果不太理想，因为我的训练集类别不均衡，有的类别数据很多有的很少，大佬有什么解决办法吗

hi，样本不均衡和多标签分类(这个repo本身)就没什么关系了。
请你自己网上搜搜吧，我知道的也都是那些，没有什么特殊的诀窍。
